### ISSUE TITLE
error when running depth_vpi.py

### ISSUE THREAD

**Issue by KuvvatGarayev** [NVIDIA-AI-IOT/jetson-stereo-depth#3]
I was able to follow the steps until depth_vpi.py where when I run python3 depth_vpi.py I get below error:
Reading camera calibration...

Traceback (most recent call last):

  File "depth_vpi.py", line 229, in <module>

    depth = Depth()

  File "depth_vpi.py", line 19, in __init__

    self._cam_r = CameraThread(0)

  File "depth_vpi.py", line 196, in __init__

    self._camera = Camera(sensor_id)

TypeError: __init__() takes 1 positional argument but 2 were given

**Comment by tomasz-lewicki** [comment]
Are you running the exact same code in https://github.com/NVIDIA-AI-IOT/jetson-stereo-depth/blob/master/depth_pipeline_python/depth_vpi.py or did you modify it somehow?

Is it possible that you're overriding the `Camera` class somewhere?

**Comment by KuvvatGarayev** [comment]
Yes, same exact code.

**Comment by tomasz-lewicki** [comment]
I will try to reproduce that error today in hardware. What JetPack version are you running?

**Comment by KuvvatGarayev** [comment]
JetPack version: 4.6-b197
